server:
  port: 8084
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/postgres
    username: postgres
    password: password
  jpa:
    open-in-view: false
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${app.keycloak.serverurl}/realms/${app.keycloak.realm}
app:
  keycloak:
    admin:
      clientId: dog-owner-management-client
      clientSecret: 5DadURYLfQfofiHUNzaSd4pA1yCydxEa
    realm: master
    serverurl: http://localhost:9090